<?php
$this->headTitle($title);
$field = 'get'.ucfirst($displayName);
?>
<div class="row">
    <div class="col-lg-4 col-md-6 col-xs-12 col-lg-offset-4 col-md-offset-3">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <p>Are you shure you want to delete '<?php echo $this->escapeHtml($item->$field()); ?>' ?</p>
        <form method="post">
            <input type="hidden" name="id" value="<?php echo (int) $item->getId(); ?>" />
            <div class="row">
                <div class="col-xs-6">
                    <input class="btn btn-block btn-success" type="submit" name="del" value="Yes" />
                </div>
                <div class="col-xs-6">
                    <input class="btn btn-block btn-danger" type="submit" name="del" value="No" />
                </div>
            </div>
        </form>
    </div>
</div>
