<?php
$this->headTitle($title);
?>
<a href="<?=$this->url($route, array('action' => 'add'))?>"><?=$this->translate($addLabel)?></a>
<div class="row">
    <div class="col-lg-8">
        <h3><?=$this->translate('List')?></h3>
        <table class="table">
            <tr>
                <?php foreach ($fields as $fieldName => $fieldLabel):?>
                <th><?=$this->translate($fieldLabel)?></th>
                <?php endforeach;?>
                <th></th>
            </tr>
            <?php foreach ($items as $i):?>
            <tr>
                <?php foreach ($fields as $fieldName => $fieldLabel):?>
                <td><?php
                    $getter = 'get' . ucfirst($fieldName);
                    echo $i->$getter();
                ?></td>
                <?php endforeach;?>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-list"></span>&nbsp;&nbsp;<?=$this->translate('Actions')?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?=$this->url($route, array('action' => 'update', 'id' => $i->getId()))?>"><i class="glyphicon glyphicon-edit"></i> <?=$this->translate('Update')?></a></li>
                            <li><a href="<?=$this->url($route, array('action' => 'delete', 'id' => $i->getId()))?>"><i class="glyphicon glyphicon-trash"></i> <?=$this->translate('Delete')?></a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>